# Generated by Django 3.2.5 on 2021-07-06 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Navbar',
            fields=[
                ('inst', models.CharField(max_length=1000, primary_key='inst', serialize=False, verbose_name='Instagram')),
                ('facebook', models.CharField(max_length=1000, verbose_name='Facebook')),
                ('email', models.CharField(max_length=1000, verbose_name='Gmail')),
                ('number1', models.CharField(max_length=13, verbose_name='Номер телефона #1')),
                ('number2', models.CharField(max_length=13, verbose_name='Номер телефона #2')),
            ],
        ),
    ]
