# Generated by Django 3.2.5 on 2021-07-30 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_bucha_gostomel_irpin_kiev_stoyanka_vorzel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bucha',
            name='comerc',
            field=models.CharField(max_length=1000, verbose_name='Комерція'),
        ),
        migrations.AlterField(
            model_name='bucha',
            name='flat',
            field=models.CharField(max_length=1000, verbose_name='Квартири'),
        ),
        migrations.AlterField(
            model_name='bucha',
            name='houses',
            field=models.CharField(max_length=1000, verbose_name='Дома'),
        ),
        migrations.AlterField(
            model_name='bucha',
            name='land',
            field=models.CharField(max_length=1000, verbose_name='Земля'),
        ),
        migrations.AlterField(
            model_name='gostomel',
            name='comerc',
            field=models.CharField(max_length=1000, verbose_name='Комерція'),
        ),
        migrations.AlterField(
            model_name='gostomel',
            name='flat',
            field=models.CharField(max_length=1000, verbose_name='Квартири'),
        ),
        migrations.AlterField(
            model_name='gostomel',
            name='houses',
            field=models.CharField(max_length=1000, verbose_name='Дома'),
        ),
        migrations.AlterField(
            model_name='gostomel',
            name='land',
            field=models.CharField(max_length=1000, verbose_name='Земля'),
        ),
        migrations.AlterField(
            model_name='irpin',
            name='comerc',
            field=models.CharField(max_length=1000, verbose_name='Комерція'),
        ),
        migrations.AlterField(
            model_name='irpin',
            name='flat',
            field=models.CharField(max_length=1000, verbose_name='Квартири'),
        ),
        migrations.AlterField(
            model_name='irpin',
            name='houses',
            field=models.CharField(max_length=1000, verbose_name='Дома'),
        ),
        migrations.AlterField(
            model_name='irpin',
            name='land',
            field=models.CharField(max_length=1000, verbose_name='Земля'),
        ),
        migrations.AlterField(
            model_name='kiev',
            name='comerc',
            field=models.CharField(max_length=1000, verbose_name='Комерція'),
        ),
        migrations.AlterField(
            model_name='kiev',
            name='flat',
            field=models.CharField(max_length=1000, verbose_name='Квартири'),
        ),
        migrations.AlterField(
            model_name='kiev',
            name='houses',
            field=models.CharField(max_length=1000, verbose_name='Дома'),
        ),
        migrations.AlterField(
            model_name='kiev',
            name='land',
            field=models.CharField(max_length=1000, verbose_name='Земля'),
        ),
        migrations.AlterField(
            model_name='stoyanka',
            name='comerc',
            field=models.CharField(max_length=1000, verbose_name='Комерція'),
        ),
        migrations.AlterField(
            model_name='stoyanka',
            name='flat',
            field=models.CharField(max_length=1000, verbose_name='Квартири'),
        ),
        migrations.AlterField(
            model_name='stoyanka',
            name='houses',
            field=models.CharField(max_length=1000, verbose_name='Дома'),
        ),
        migrations.AlterField(
            model_name='stoyanka',
            name='land',
            field=models.CharField(max_length=1000, verbose_name='Земля'),
        ),
        migrations.AlterField(
            model_name='vorzel',
            name='comerc',
            field=models.CharField(max_length=1000, verbose_name='Комерція'),
        ),
        migrations.AlterField(
            model_name='vorzel',
            name='flat',
            field=models.CharField(max_length=1000, verbose_name='Квартири'),
        ),
        migrations.AlterField(
            model_name='vorzel',
            name='houses',
            field=models.CharField(max_length=1000, verbose_name='Дома'),
        ),
    ]
